### ISSUE TITLE
instal?

### ISSUE THREAD

**Issue by Mafiasz12** [jmatg1/lords-mobile-bot#1]
how instal

**Comment by LoveGerl** [comment]
я непонял одного как указать путь всё остальное понятно

**Comment by maldini89** [comment]
- open cmd
- go to path boot (file requirements.txt in this location) type in the cmd: cd %folderpath%
- type text: py -m pip install -r requirements.txt
and wait

**Comment by japit44** [comment]
error...

Traceback (most recent call last):
  File "E:\lords-mobile-bot-main\code.py", line 445, in <module>
    devList = check_output("hd-adb devices")
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by jmatg1** [comment]
> error...
> 
> Traceback (most recent call last): File "E:\lords-mobile-bot-main\code.py", line 445, in devList = check_output("hd-adb devices") File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 420, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified

YOu need istall pyton Python 3.9.1 https://www.python.org/downloads/release/python-391/
3.9.1 version important
and bot it doesnt work, because game updated and it have new graph

**Comment by japit44** [comment]
is there a new source?

**Comment by japit44** [comment]
i already installed Python 3.9.1 https://www.python.org/downloads/release/python-391/
3.9.1 version important
