### ISSUE TITLE
Get an error during Execution

### ISSUE THREAD

**Issue by russianguyx** [jmatg1/lords-mobile-bot#3]
File "C:\Users\rachi\Desktop\FreeBotLords\lords-mobile-bot-main\code.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

This is what I get after I run code.py

**Comment by russianguyx** [comment]
C:\Users\rachi\Desktop\FreeBotLords\lords-mobile-bot-main>python code.py
b'List of devices attached\r\nemulator-5554\tdevice\r\n\r\n'
ARRAY DEVICES ['emulator-5554']
['emulator-5554']
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\rachi\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\rachi\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "code.py", line 110, in main
    self.getScreen()
  File "code.py", line 87, in getScreen
    self.screenshot = Image.open(f"{self.screenshotName}")
  File "C:\Users\rachi\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'emulator-5554-screenshot.png'

Found out my error, but still getting another one now after running the GUI

**Comment by russianguyx** [comment]
How do I set position so the bot actually does what it's suppose to do?
